version: '3'

services:

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/dev/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./docker/dev/keycloak-schema.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      MYSQL_ROOT_PASSWORD: agri
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=agri --execute \"SHOW DATABASES;\""
      interval: 100s
      retries: 10
    networks:
      - Agri

  mysql-client:
    image: dbeaver/cloudbeaver:latest
    container_name: mysql-client
    volumes:
      - mysql-client:/opt/cloudbeaver/workspace
    ports:
      - 3300:8978
    restart: unless-stopped
    networks:
      - Agri


  nextcloud:
    build:
      context: ./docker/nextCloud
    image: nextcloud:22.0.0
    container_name: nextcloud
    restart: always
    ports:
      - 3900:80
    volumes:
      - nextcloud:/var/www/html/data
    environment:
      MYSQL_PASSWORD: agri
      MYSQL_DATABASE: agri_activity_cloud
      MYSQL_USER: root
      MYSQL_HOST: mysql
    networks:
      - Agri

networks:
  Agri:
    driver: bridge

volumes:
  mysql:
  mysql-client:
  nextcloud:
