version: '3'

services:

  myysql:
    image: mysql:8.0.26
    container_name: myysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: agri
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=mysecretpassword --execute \"SHOW DATABASES;\""
      interval: 100s
      retries: 10

#  keycloak:
#    container_name: keycloak
#    build:
#      context: .
#      dockerfile: ./docker/keycloak/Dockerfile
#    environment:
#      DB_VENDOR: MYSQL
#      DB_USER: root
#      DB_DATABASE: Agri_keycloak
#      DB_PASSWORD: Agri
#      DB_ADDR: mysql
#    volumes:
#      - ./docker/keycloak/themes/activity_theme:/opt/jboss/keycloak/themes/activity_theme
#    ports:
#      - 3800:8080
#    networks:
#      - norsys





