
server:
  port: 8090
  http2:
    enabled: true

spring:
  profiles:
    active: dev
  datasource:
    password: mysecretpassword
    url: jdbc:mysql://localhost:3306/norsys_activity
    username: root

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 11MB

  #  mvc:
  #    hiddenmethod:
  #      filter:
  #        enabled: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

